### ISSUE TITLE
7.1.0 Crashes in DynamicFormInstancesService despite not using it anywhere in App

### ISSUE THREAD

**Issue by rernens** [udos86/ng-dynamic-forms#924]
## I'm submitting a

<pre><code>
[X] Bug / Regression
[ ] Feature Request / Proposal
[ ] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `7.1.0`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[X] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description

After upgrading to 7.1.0, my applications stopped working when switching from one component to another within the same module when ng-dynamic-forms are used in both.

Problem occurs in new DynamicFormInstancesService despite not using it anywhere so far  :

```
core.js:15714 ERROR Error: Uncaught (in promise): Error: There exists no control with id: search
Error: There exists no control with id: search
    at DynamicFormInstancesService.push.../../node_modules/@ng-dynamic-forms/core/fesm5/core.js.DynamicFormInstancesService.removeFormControlInstance (core.js:10115)
    at DynamicMaterialFormControlContainerComponent.push.../../node_modules/@ng-dynamic-forms/core/fesm5/core.js.DynamicFormControlContainerComponent.removeInstance (core.js:7780)
    at DynamicMaterialFormControlContainerComponent.push.../../node_modules/@ng-dynamic-forms/core/fesm5/core.js.DynamicFormControlContainerComponent.destroyFormControlComponent (core.js:7474)
    at DynamicMaterialFormControlContainerComponent.push.../../node_modules/@ng-dynamic-forms/core/fesm5/core.js.DynamicFormControlContainerComponent.ngOnDestroy (core.js:7289)
```

The issue comes from the fact that several form models are using the same control id for fields ( i.e search ). In the case above, two components appearing on the same page have a search field that are used to search the relevant list of information provided in the associated component as shown in the screenshot below.

![image](https://user-images.githubusercontent.com/10088036/52261761-ac719180-292a-11e9-834a-1fd6225ea157.png)

The main component has 2 children components, each of them having two children components ( a list with a search form - what you see above - an a detail form triggered by the + button that displays in a modal to add a new entry in the list ).

As far as I can see you build a formControlInstances object that contains the various controls found in the main component not at the underlying component level and there is a single entry in that list for a named control ( so only one entry for the search control despite, those coming from different formModels in different components ).

In my case, and certainly not only in my case, this won't work as I am reusing models in various components as long as they work the same ( ie search form ).

**Comment by udos86** [comment]
@Karamuto Could you please help out here

**Comment by Karamuto** [comment]
Hello @rernens,

you seem right there, I really havn't thought of this.

As as a workaround, so you can keep working use this:

```
export class OverrideInstanceService extends DynamicFormInstancesService {

    getFormControlInstance(modelId: string, index?: number): ComponentRef<DynamicFormControl> | undefined {
        return undefined;
    }

    removeFormControlInstance(modelId: string, index?: number): void | never {
        return undefined;
    }

    setFormControlInstance(model: DynamicFormControlModel, instance: ComponentRef<DynamicFormControl>, index?: number): void {
    }
    
}
```

and provide it for the DynamicFormInstanceService, this should at least make your app usable again.

**Comment by rernens** [comment]
@Karamuto 

Thanks for your workaround but as nothing in 7.1.0 is critical for me at that stage as Udo has not found why building in prod with optimization on renders the custom validators unusable, I'll stick to 7.0.4 until further notice.

Thanks anyway.

**Comment by rernens** [comment]
@Karamuto 

for the custom validator issue see #918

**Comment by phgachoud** [comment]
Same problem for me, seems that I have to refactor so that all DynamicInputModel have different ids...

**Comment by Karamuto** [comment]
Hello @phgachoud ,

no need for that, just use the upper service while the fix is not merged.

I am sorry for your troubles.

**Comment by phgachoud** [comment]
> DynamicFormInstanceService



> Hello @rernens,
> 
> you seem right there, I really havn't thought of this.
> 
> As as a workaround, so you can keep working use this:
> 
> ```
> export class OverrideInstanceService extends DynamicFormInstancesService {
> 
>     getFormControlInstance(modelId: string, index?: number): ComponentRef<DynamicFormControl> | undefined {
>         return undefined;
>     }
> 
>     removeFormControlInstance(modelId: string, index?: number): void | never {
>         return undefined;
>     }
> 
>     setFormControlInstance(model: DynamicFormControlModel, instance: ComponentRef<DynamicFormControl>, index?: number): void {
>     }
>     
> }
> ```
> 
> and provide it for the DynamicFormInstanceService, this should at least make your app usable again.
If you could provide the imports and how to add it (app.module.ts I suppose) it'll be of great help for newbies ;-)
