### ISSUE TITLE
errors when upgrading to 11.0.3

### ISSUE THREAD

**Issue by drkhannah** [udos86/ng-dynamic-forms#1081]
## I'm submitting a

<pre><code>
[x] Bug / Regression
[ ] Feature Request / Proposal
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `11.0.3`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[ ] Material  
[ ] NG Bootstrap
[x ] Prime NG
</code></pre>

## Description
Hello thanks for this awesome lib i've been using it for a while

I just upgraded to 11.0.3 and i started getting these errors when i build my project

```ERROR in node_modules/@ng-dynamic-forms/core/lib/component/dynamic-form-array.component.d.ts:11:9 - error TS1086: An accessor cannot be declared in an ambient context.

11     get array(): FormArray;
           ~~~~~
node_modules/@ng-dynamic-forms/core/lib/component/dynamic-form-array.component.d.ts:12:9 - error TS1086: An accessor cannot be declared in an ambient context.

12     get startTemplate(): DynamicTemplateDirective | undefined;
           ~~~~~~~~~~~~~
node_modules/@ng-dynamic-forms/core/lib/component/dynamic-form-array.component.d.ts:13:9 - error TS1086: An accessor cannot be declared in an ambient context.

13     get endTemplate(): DynamicTemplateDirective | undefined;
           ~~~~~~~~~~~
node_modules/@ng-dynamic-forms/core/lib/component/dynamic-form-control-container.component.d.ts:43:18 - error TS1086: An accessor cannot be declared in an ambient context.

43     abstract get componentType(): Type<DynamicFormControl> | null;
                    ~~~~~~~~~~~~~
node_modules/@ng-dynamic-forms/core/lib/component/dynamic-form-control-container.component.d.ts:44:9 - error TS1086: An accessor cannot be declared in an ambient context.

44     get id(): string;
           ~~
node_modules/@ng-dynamic-forms/core/lib/component/dynamic-form-control-container.component.d.ts:45:9 - error TS1086: An accessor cannot be declared in an ambient context.

45     get hasFocus(): boolean;
           ~~~~~~~~
node_modules/@ng-dynamic-forms/core/lib/component/dynamic-form-control-container.component.d.ts:46:9 - error TS1086: An accessor cannot be declared in an ambient context.

46     get isInvalid(): boolean;
           ~~~~~~~~~
node_modules/@ng-dynamic-forms/core/lib/component/dynamic-form-control-container.component.d.ts:47:9 - error TS1086: An accessor cannot be declared in an ambient context.

47     get isValid(): boolean;
           ~~~~~~~
node_modules/@ng-dynamic-forms/core/lib/component/dynamic-form-control-container.component.d.ts:48:9 - error TS1086: An accessor cannot be declared in an ambient context.

48     get errorMessages(): string[];
           ~~~~~~~~~~~~~
node_modules/@ng-dynamic-forms/core/lib/component/dynamic-form-control-container.component.d.ts:49:9 - error TS1086: An accessor cannot be declared in an ambient context.

49     get showErrorMessages(): boolean;
           ~~~~~~~~~~~~~~~~~
node_modules/@ng-dynamic-forms/core/lib/component/dynamic-form-control-container.component.d.ts:50:9 - error TS1086: An accessor cannot be declared in an ambient context.

50     get hasLabel(): boolean;
           ~~~~~~~~
node_modules/@ng-dynamic-forms/core/lib/component/dynamic-form-control-container.component.d.ts:51:9 - error TS1086: An accessor cannot be declared in an ambient context.

51     get hasHint(): boolean;
           ~~~~~~~
node_modules/@ng-dynamic-forms/core/lib/component/dynamic-form-control-container.component.d.ts:52:9 - error TS1086: An accessor cannot be declared in an ambient context.

52     get hint(): string | null;
           ~~~~
node_modules/@ng-dynamic-forms/core/lib/component/dynamic-form-control-container.component.d.ts:53:9 - error TS1086: An accessor cannot be declared in an ambient context.

53     get isCheckbox(): boolean;
           ~~~~~~~~~~
node_modules/@ng-dynamic-forms/core/lib/component/dynamic-form-control-container.component.d.ts:54:9 - error TS1086: An accessor cannot be declared in an ambient context.

54     get templates(): QueryList<DynamicTemplateDirective> | undefined;
           ~~~~~~~~~
node_modules/@ng-dynamic-forms/core/lib/component/dynamic-form-control-container.component.d.ts:55:9 - error TS1086: An accessor cannot be declared in an ambient context.

55     get startTemplate(): DynamicTemplateDirective | undefined;
           ~~~~~~~~~~~~~
node_modules/@ng-dynamic-forms/core/lib/component/dynamic-form-control-container.component.d.ts:56:9 - error TS1086: An accessor cannot be declared in an ambient context.

56     get endTemplate(): DynamicTemplateDirective | undefined;
           ~~~~~~~~~~~
node_modules/@ng-dynamic-forms/core/lib/component/dynamic-form-control-with-template.component.d.ts:14:18 - error TS1086: An accessor cannot be declared in an ambient context.

14     abstract get viewChild(): any;
                    ~~~~~~~~~
node_modules/@ng-dynamic-forms/core/lib/component/dynamic-form-control.component.d.ts:23:9 - error TS1086: An accessor cannot be declared in an ambient context.

23     get control(): AbstractControl | never;
           ~~~~~~~
node_modules/@ng-dynamic-forms/core/lib/component/dynamic-form-control.component.d.ts:24:9 - error TS1086: An accessor cannot be declared in an ambient context.

24     get id(): string;
           ~~
node_modules/@ng-dynamic-forms/core/lib/component/dynamic-form-control.component.d.ts:25:9 - error TS1086: An accessor cannot be declared in an ambient context.

25     get hasFocus(): boolean;
           ~~~~~~~~
node_modules/@ng-dynamic-forms/core/lib/component/dynamic-form-control.component.d.ts:26:9 - error TS1086: An accessor cannot be declared in an ambient context.

26     get isInvalid(): boolean;
           ~~~~~~~~~
node_modules/@ng-dynamic-forms/core/lib/component/dynamic-form-control.component.d.ts:27:9 - error TS1086: An accessor cannot be declared in an ambient context.

27     get isValid(): boolean;
           ~~~~~~~
node_modules/@ng-dynamic-forms/core/lib/component/dynamic-form-control.component.d.ts:28:9 - error TS1086: An accessor cannot be declared in an ambient context.

28     get errorMessages(): string[];
           ~~~~~~~~~~~~~
node_modules/@ng-dynamic-forms/core/lib/component/dynamic-form-control.component.d.ts:29:9 - error TS1086: An accessor cannot be declared in an ambient context.

29     get showErrorMessages(): boolean;
           ~~~~~~~~~~~~~~~~~
node_modules/@ng-dynamic-forms/core/lib/model/dynamic-check-control.model.d.ts:9:9 - error TS1086: An accessor cannot be declared in an ambient context.

9     get checked(): boolean;
          ~~~~~~~
node_modules/@ng-dynamic-forms/core/lib/model/dynamic-check-control.model.d.ts:10:9 - error TS1086: An accessor cannot be declared in an ambient context.

10     set checked(checked: boolean);
           ~~~~~~~
node_modules/@ng-dynamic-forms/core/lib/model/dynamic-form-control.model.d.ts:39:9 - error TS1086: An accessor cannot be declared in an ambient context.

39     get disabled(): boolean;
           ~~~~~~~~
node_modules/@ng-dynamic-forms/core/lib/model/dynamic-form-control.model.d.ts:40:9 - error TS1086: An accessor cannot be declared in an ambient context.

40     set disabled(disabled: boolean);
           ~~~~~~~~
node_modules/@ng-dynamic-forms/core/lib/model/dynamic-form-control.model.d.ts:41:9 - error TS1086: An accessor cannot be declared in an ambient context.

41     get hasErrorMessages(): boolean;
           ~~~~~~~~~~~~~~~~
node_modules/@ng-dynamic-forms/core/lib/model/dynamic-form-value-control.model.d.ts:24:9 - error TS1086: An accessor cannot be declared in an ambient context.

24     get value(): T | null;
           ~~~~~
node_modules/@ng-dynamic-forms/core/lib/model/dynamic-form-value-control.model.d.ts:25:9 - error TS1086: An accessor cannot be declared in an ambient context.

25     set value(value: T | null);
           ~~~~~
node_modules/@ng-dynamic-forms/core/lib/model/dynamic-option-control.model.d.ts:14:9 - error TS1086: An accessor cannot be declared in an ambient context.

14     get text(): string | null;
           ~~~~
node_modules/@ng-dynamic-forms/core/lib/model/dynamic-option-control.model.d.ts:15:9 - error TS1086: An accessor cannot be declared in an ambient context.

15     set text(text: string | null);
           ~~~~
node_modules/@ng-dynamic-forms/core/lib/model/dynamic-option-control.model.d.ts:26:9 - error TS1086: An accessor cannot be declared in an ambient context.

26     set options(options: any);
           ~~~~~~~
node_modules/@ng-dynamic-forms/core/lib/model/dynamic-option-control.model.d.ts:27:9 - error TS1086: An accessor cannot be declared in an ambient context.

27     get options(): any;
           ~~~~~~~
node_modules/@ng-dynamic-forms/core/lib/model/form-array/dynamic-form-array.model.d.ts:12:9 - error TS1086: An accessor cannot be declared in an ambient context.

12     get parent(): DynamicFormArrayModel;
           ~~~~~~
node_modules/@ng-dynamic-forms/core/lib/model/form-array/dynamic-form-array.model.d.ts:34:9 - error TS1086: An accessor cannot be declared in an ambient context.

34     get size(): number;
           ~~~~
node_modules/@ng-dynamic-forms/core/lib/model/input/dynamic-input.model.d.ts:46:9 - error TS1086: An accessor cannot be declared in an ambient context.

46     get listId(): string | null;
           ~~~~~~
node_modules/@ng-dynamic-forms/core/lib/model/input/dynamic-input.model.d.ts:47:9 - error TS1086: An accessor cannot be declared in an ambient context.

47     get hasList(): boolean;
           ~~~~~~~
node_modules/@ng-dynamic-forms/core/lib/model/input/dynamic-input.model.d.ts:48:9 - error TS1086: An accessor cannot be declared in an ambient context.

48     set list(list: any[] | Observable<any[]> | null);
           ~~~~
node_modules/@ng-dynamic-forms/ui-primeng/lib/autocomplete/dynamic-primeng-autocomplete.component.d.ts:22:9 - error TS1086: An accessor cannot be declared in an ambient context.

22     get suggestions(): string[];
           ~~~~~~~~~~~
node_modules/@ng-dynamic-forms/ui-primeng/lib/autocomplete/dynamic-primeng-autocomplete.component.d.ts:23:9 - error TS1086: An accessor cannot be declared in an ambient context.

23     get viewChild(): AutoComplete;
           ~~~~~~~~~
node_modules/@ng-dynamic-forms/ui-primeng/lib/calendar/dynamic-primeng-calendar.component.d.ts:18:9 - error TS1086: An accessor cannot be declared in an ambient context.

18     get focusedDate(): DynamicDateControlValue | null;
           ~~~~~~~~~~~
node_modules/@ng-dynamic-forms/ui-primeng/lib/calendar/dynamic-primeng-calendar.component.d.ts:19:9 - error TS1086: An accessor cannot be declared in an ambient context.

19     get inline(): boolean;
           ~~~~~~
node_modules/@ng-dynamic-forms/ui-primeng/lib/calendar/dynamic-primeng-calendar.component.d.ts:20:9 - error TS1086: An accessor cannot be declared in an ambient context.

20     get showSeconds(): boolean;
           ~~~~~~~~~~~
node_modules/@ng-dynamic-forms/ui-primeng/lib/chips/dynamic-primeng-chips.component.d.ts:21:9 - error TS1086: An accessor cannot be declared in an ambient context.

21     get viewChild(): Chips;
           ~~~~~~~~~
node_modules/@ng-dynamic-forms/ui-primeng/lib/dropdown/dynamic-primeng-dropdown.component.d.ts:20:9[0[39mm - error TS1086: An accessor cannot be declared in an ambient context.

20     get viewChild(): Dropdown;
           ~~~~~~~~~
node_modules/@ng-dynamic-forms/ui-primeng/lib/dynamic-primeng-form-control-container.component.d.ts:25:9 - error TS1086: An accessor cannot be declared in an ambient context.

25     get componentType(): Type<DynamicFormControl> | null;
```

**Comment by drkhannah** [comment]
im also getting this error in my code
<img width="763" alt="Screen Shot 2020-05-06 at 4 30 40 PM" src="https://user-images.githubusercontent.com/6707443/81225288-fe361b00-8fb6-11ea-80ed-ef45af877c04.png">

**Comment by Bhuvan-Arora** [comment]
@drkhannah You closed this issue, That means it is resolved at your end. It would be really great, if you can provide the fix in the trail. :)

**Comment by drkhannah** [comment]
I think I had to upgrade the the latest angular version
