### ISSUE TITLE
MATCHER errors after upgrading to 10.1.0

### ISSUE THREAD

**Issue by drkhannah** [udos86/ng-dynamic-forms#1062]
## I'm submitting a

<pre><code>
[ x] Bug / Regression
[ ] Feature Request / Proposal
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `X.Y.Z`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[ ] Material  
[ ] NG Bootstrap
[s ] Prime NG
</code></pre>

## Description
I just upgraded from 8.1.0 to 10.1.0 and I am getting errors about MATCHERs when building 

ERROR in src/app/app.module.ts:75:5 - error TS2322: Type 'DynamicFormControlMatcher' is not assignable to type 'Provider'.
  Type 'DynamicFormControlMatcher' is missing the following properties from type 'TypeProvider': apply, call, bind, prototype, and 5 more.

75     DISABLED_MATCHER,
       ~~~~~~~~~~~~~~~~
src/app/app.module.ts:76:5 - error TS2322: Type 'DynamicFormControlMatcher' is not assignable to type 'Provider'.
  Type 'DynamicFormControlMatcher' is not assignable to type 'TypeProvider'.

76     REQUIRED_MATCHER,
       ~~~~~~~~~~~~~~~~
src/app/app.module.ts:77:5 - error TS2322: Type 'DynamicFormControlMatcher' is not assignable to type 'Provider'.
  Type 'DynamicFormControlMatcher' is not assignable to type 'TypeProvider'.

77     HIDDEN_MATCHER
       ~~~~~~~~~~~~~~

**Comment by drkhannah** [comment]
i fixed it by adding ...DYNAMIC_MATCHER_PROVIDERS
